// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#ifndef __BINDINGS_BINDINGS_H
#define __BINDINGS_BINDINGS_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct bindings_string_t {
  uint8_t*ptr;
  size_t len;
} bindings_string_t;

typedef struct {
  bool is_err;
  union {
    bindings_string_t err;
  } val;
} runtime_result_void_string_t;

typedef struct {
  bool is_err;
  union {
    bindings_string_t ok;
    bindings_string_t err;
  } val;
} runtime_result_string_string_t;

// Imported Functions from `local:bindings/host`
extern void local_bindings_host_log(bindings_string_t *msg);
extern uint32_t local_bindings_host_random_u32(void);

// Exported Functions from `runtime`
bool runtime_init(bindings_string_t *err);
bool runtime_eval(bindings_string_t *source, bindings_string_t *ret, bindings_string_t *err);

// Helper Functions

void runtime_result_void_string_free(runtime_result_void_string_t *ptr);

void runtime_result_string_string_free(runtime_result_string_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void bindings_string_set(bindings_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void bindings_string_dup(bindings_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void bindings_string_dup_n(bindings_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void bindings_string_free(bindings_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
