// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#ifndef __BINDINGS_JS_PLUGIN_H
#define __BINDINGS_JS_PLUGIN_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct js_plugin_string_t {
  uint8_t*ptr;
  size_t len;
} js_plugin_string_t;

typedef struct {
  bool is_err;
  union {
    js_plugin_string_t ok;
    js_plugin_string_t err;
  } val;
} gams_runtime_runtime_result_string_string_t;

typedef struct {
  bool is_err;
  union {
    js_plugin_string_t ok;
    js_plugin_string_t err;
  } val;
} exports_gams_js_js_result_string_string_t;

// Imported Functions from `gams:runtime/runtime@1.0.0`
// Dynamic call from a WASM component to the host runtime.
extern bool gams_runtime_runtime_call(js_plugin_string_t *target, js_plugin_string_t *args, js_plugin_string_t *ret, js_plugin_string_t *err);

// Exported Functions from `gams:js/js@1.0.0`
bool exports_gams_js_js_run(js_plugin_string_t *source, js_plugin_string_t *ret, js_plugin_string_t *err);

// Helper Functions

void gams_runtime_runtime_result_string_string_free(gams_runtime_runtime_result_string_string_t *ptr);

void exports_gams_js_js_result_string_string_free(exports_gams_js_js_result_string_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void js_plugin_string_set(js_plugin_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void js_plugin_string_dup(js_plugin_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void js_plugin_string_dup_n(js_plugin_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void js_plugin_string_free(js_plugin_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
