// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#include "js_plugin.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `gams:runtime/runtime@1.0.0`

__attribute__((__import_module__("gams:runtime/runtime@1.0.0"), __import_name__("call")))
extern void __wasm_import_gams_runtime_runtime_call(uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

// Exported Functions from `gams:js/js@1.0.0`

__attribute__((__weak__, __export_name__("cabi_post_gams:js/js@1.0.0#run")))
void __wasm_export_exports_gams_js_js_run_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(3*sizeof(void*))];

// Helper Functions

void gams_runtime_runtime_result_string_string_free(gams_runtime_runtime_result_string_string_t *ptr) {
  if (!ptr->is_err) {
    js_plugin_string_free(&ptr->val.ok);
  } else {
    js_plugin_string_free(&ptr->val.err);
  }
}

void exports_gams_js_js_result_string_string_free(exports_gams_js_js_result_string_string_t *ptr) {
  if (!ptr->is_err) {
    js_plugin_string_free(&ptr->val.ok);
  } else {
    js_plugin_string_free(&ptr->val.err);
  }
}

void js_plugin_string_set(js_plugin_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void js_plugin_string_dup(js_plugin_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void js_plugin_string_dup_n(js_plugin_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void js_plugin_string_free(js_plugin_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

bool gams_runtime_runtime_call(js_plugin_string_t *target, js_plugin_string_t *args, js_plugin_string_t *ret, js_plugin_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_gams_runtime_runtime_call((uint8_t *) (*target).ptr, (*target).len, (uint8_t *) (*args).ptr, (*args).len, ptr);
  gams_runtime_runtime_result_string_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (js_plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (js_plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

__attribute__((__export_name__("gams:js/js@1.0.0#run")))
uint8_t * __wasm_export_exports_gams_js_js_run(uint8_t * arg, size_t arg0) {
  js_plugin_string_t arg1 = (js_plugin_string_t) { (uint8_t*)(arg), (arg0) };
  exports_gams_js_js_result_string_string_t ret;
  js_plugin_string_t ok;
  js_plugin_string_t err;
  ret.is_err = !exports_gams_js_js_run(&arg1, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const js_plugin_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload2).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload2).ptr;
  } else {
    const js_plugin_string_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_js_plugin(void);
__attribute__((used))
void __component_type_object_force_link_js_plugin_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_js_plugin();
}
