// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#ifndef __BINDINGS_STARLING_LITE_H
#define __BINDINGS_STARLING_LITE_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct starling_lite_string_t {
  uint8_t*ptr;
  size_t len;
} starling_lite_string_t;

typedef struct {
  bool is_err;
  union {
    starling_lite_string_t err;
  } val;
} exports_my_starling_lite_runtime_result_void_string_t;

typedef struct {
  bool is_err;
  union {
    starling_lite_string_t ok;
    starling_lite_string_t err;
  } val;
} exports_my_starling_lite_runtime_result_string_string_t;

// Imported Functions from `my:starling-lite/host`
extern void my_starling_lite_host_log(starling_lite_string_t *msg);
extern uint32_t my_starling_lite_host_random_u32(void);

// Exported Functions from `my:starling-lite/runtime`
bool exports_my_starling_lite_runtime_init(starling_lite_string_t *err);
bool exports_my_starling_lite_runtime_eval(starling_lite_string_t *source, starling_lite_string_t *ret, starling_lite_string_t *err);

// Helper Functions

void exports_my_starling_lite_runtime_result_void_string_free(exports_my_starling_lite_runtime_result_void_string_t *ptr);

void exports_my_starling_lite_runtime_result_string_string_free(exports_my_starling_lite_runtime_result_string_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void starling_lite_string_set(starling_lite_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void starling_lite_string_dup(starling_lite_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void starling_lite_string_dup_n(starling_lite_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void starling_lite_string_free(starling_lite_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
