// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#include "starling_lite.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `my:starling-lite/host`

__attribute__((__import_module__("my:starling-lite/host"), __import_name__("log")))
extern void __wasm_import_my_starling_lite_host_log(uint8_t *, size_t);

__attribute__((__import_module__("my:starling-lite/host"), __import_name__("random-u32")))
extern int32_t __wasm_import_my_starling_lite_host_random_u32(void);

// Exported Functions from `my:starling-lite/runtime`

__attribute__((__weak__, __export_name__("cabi_post_my:starling-lite/runtime#init")))
void __wasm_export_exports_my_starling_lite_runtime_init_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_my:starling-lite/runtime#eval")))
void __wasm_export_exports_my_starling_lite_runtime_eval_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(3*sizeof(void*))];

// Helper Functions

void exports_my_starling_lite_runtime_result_void_string_free(exports_my_starling_lite_runtime_result_void_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    starling_lite_string_free(&ptr->val.err);
  }
}

void exports_my_starling_lite_runtime_result_string_string_free(exports_my_starling_lite_runtime_result_string_string_t *ptr) {
  if (!ptr->is_err) {
    starling_lite_string_free(&ptr->val.ok);
  } else {
    starling_lite_string_free(&ptr->val.err);
  }
}

void starling_lite_string_set(starling_lite_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void starling_lite_string_dup(starling_lite_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void starling_lite_string_dup_n(starling_lite_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void starling_lite_string_free(starling_lite_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void my_starling_lite_host_log(starling_lite_string_t *msg) {
  __wasm_import_my_starling_lite_host_log((uint8_t *) (*msg).ptr, (*msg).len);
}

uint32_t my_starling_lite_host_random_u32(void) {
  int32_t ret = __wasm_import_my_starling_lite_host_random_u32();
  return (uint32_t) (ret);
}

__attribute__((__export_name__("my:starling-lite/runtime#init")))
uint8_t * __wasm_export_exports_my_starling_lite_runtime_init(void) {
  exports_my_starling_lite_runtime_result_void_string_t ret;
  starling_lite_string_t err;
  ret.is_err = !exports_my_starling_lite_runtime_init(&err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const starling_lite_string_t *payload0 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload0).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload0).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

__attribute__((__export_name__("my:starling-lite/runtime#eval")))
uint8_t * __wasm_export_exports_my_starling_lite_runtime_eval(uint8_t * arg, size_t arg0) {
  starling_lite_string_t arg1 = (starling_lite_string_t) { (uint8_t*)(arg), (arg0) };
  exports_my_starling_lite_runtime_result_string_string_t ret;
  starling_lite_string_t ok;
  starling_lite_string_t err;
  ret.is_err = !exports_my_starling_lite_runtime_eval(&arg1, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const starling_lite_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload2).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload2).ptr;
  } else {
    const starling_lite_string_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_starling_lite(void);
__attribute__((used))
void __component_type_object_force_link_starling_lite_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_starling_lite();
}
