if(CMAKE_SCRIPT_MODE_FILE)
    return()
endif()

add_library(builtins STATIC builtins/install_builtins.cpp)
target_include_directories(builtins PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
target_link_libraries(builtins PRIVATE extension_api)

include("add_builtin")

set(INSTALL_BUILTINS ${CMAKE_CURRENT_BINARY_DIR}/builtins.incl CACHE INTERNAL "Path to generated builtins.incl" FORCE)
file(WRITE ${INSTALL_BUILTINS} "// This file is generated by CMake\n")

add_builtin(
    builtins::gams::host
    SRC
        builtins/gams/host.cpp
    DEPENDENCIES
        host_api
    INCLUDE_DIRS
        runtime
        ${HOST_API}/bindings
)
